name: jest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Jest Snapshots
      uses: gimenete/github-jest-snapshots@1.0
    - run: npm install
    - run: npm run build --if-present
    - run: npx eslint .
    - run: npm test
      env:
        CI: true
